[project]
name = "fm-drug-interactions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kalutm", email = "kalebtesfahun@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
]

[project.scripts]
fm-drug-interactions = "fm_drug_interactions:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
